# Generated by Django 5.2.17 on 2026-09-01 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=127)),
                ('clientAdress', models.CharField(max_length=255)),
                ('clientCPF', models.CharField(max_length=11, unique=True)),
                ('clientEmail', models.CharField(max_length=127, unique=True)),
                ('clientPasswordHash', models.CharField(max_length=255)),
                ('clientAccountCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=127)),
                ('companyAdress', models.CharField(max_length=255)),
                ('companyCNPJ', models.CharField(max_length=18, unique=True)),
                ('companyEmail', models.CharField(max_length=127, unique=True)),
                ('companyPasswordHash', models.CharField(max_length=255)),
                ('companyAccountCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceCategory', models.CharField(max_length=45)),
                ('deviceModel', models.CharField(max_length=100)),
                ('deviceDescription', models.CharField(max_length=255)),
                ('offeredValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=127)),
                ('driverCPF', models.CharField(max_length=11, unique=True)),
                ('driverCNH', models.CharField(max_length=9, unique=True)),
                ('driverEmail', models.CharField(max_length=127, unique=True)),
                ('driverPasswordHash', models.CharField(max_length=255)),
                ('driverAccountCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField(max_length=255)),
                ('imageType', models.CharField(choices=[('initial', 'Foto inicial (oferta)'), ('confirmation', 'Foto de confirmação (entrega)')], max_length=20)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.device')),
            ],
            options={
                'db_table': 'device_image',
            },
        ),
    ]
