# Generated by Django 5.2.17 on 2026-09-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='deviceCategory',
            new_name='device_category',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='deviceDescription',
            new_name='device_description',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='deviceModel',
            new_name='device_model',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='offeredValue',
            new_name='offered_value',
        ),
    ]
