# Generated by Django 5.2.17 on 2026-09-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_createdat_device_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="client",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.client"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="current_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.company",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="device_condition",
            field=models.CharField(
                choices=[("NOVO", "Novo"), ("USADO", "Usado")], default=1, max_length=5
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="device_status",
            field=models.CharField(
                choices=[
                    ("EM_ANALISE", "Em análise"),
                    ("OFERTADO", "Ofertado"),
                    ("ACEITO", "Aceito"),
                    ("RECUSADO", "Recusado"),
                ],
                default="EM_ANALISE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="expected_offer",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="offered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_category",
            field=models.CharField(
                choices=[
                    ("GREEN", "Computadores, Tablets, Celulares"),
                    ("WHITE", "Geladeiras, Micro-ondas, Máquina de Lavar"),
                    ("BROWN", "Televisão, Rádio, Câmeras e Caixas de Som"),
                    ("BLUE", "Ferramentas Elétricas, Brinquedos eletrônicos"),
                    ("OTHER", "Meu dispositivo não se encaixa nas categorias acima"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="offered_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
