# Generated by Django 5.2.17 on 2026-09-22 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_createdat_device_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO_MOTORISTA", "Aguardando motorista"),
                            ("MOTORISTA_ACEITOU", "Motorista aceitou"),
                            ("PRODUTO_RECOLHIDO", "Produto recolhido"),
                            ("EM_TRANSITO", "Em trânsito"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="AGUARDANDO_MOTORISTA",
                        max_length=25,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides",
                        to="api.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides",
                        to="api.company",
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ride",
                        to="api.device",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rides",
                        to="api.driver",
                    ),
                ),
            ],
            options={
                "db_table": "ride",
            },
        ),
        migrations.CreateModel(
            name="RideStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO_MOTORISTA", "Aguardando motorista"),
                            ("MOTORISTA_ACEITOU", "Motorista aceitou"),
                            ("PRODUTO_RECOLHIDO", "Produto recolhido"),
                            ("EM_TRANSITO", "Em trânsito"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        max_length=25,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="api.ride",
                    ),
                ),
            ],
            options={
                "db_table": "ride_status_history",
                "ordering": ["changed_at"],
            },
        ),
    ]
