# Generated by Django 5.2.17 on 2026-09-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_device_client_device_current_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientAccountCreatedAt',
            new_name='client_account_created_at',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientAdress',
            new_name='client_adress',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientCPF',
            new_name='client_cpf',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientEmail',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientName',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientPasswordHash',
            new_name='client_password_hash',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyAccountCreatedAt',
            new_name='company_account_created_at',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyAdress',
            new_name='company_adress',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyCNPJ',
            new_name='company_cnpj',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyEmail',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyPasswordHash',
            new_name='company_password_hash',
        ),
        migrations.RenameField(
            model_name='deviceimage',
            old_name='imageType',
            new_name='image_type',
        ),
        migrations.RenameField(
            model_name='deviceimage',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='deviceimage',
            old_name='uploadedAt',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driverAccountCreatedAt',
            new_name='driver_account_created_at',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driverCNH',
            new_name='driver_cnh',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driverCPF',
            new_name='driver_cpf',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driverEmail',
            new_name='driver_email',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driverName',
            new_name='driver_name',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driverPasswordHash',
            new_name='driver_password_hash',
        ),
    ]
