# Generated by Django 5.2.17 on 2026-09-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_device_client_device_current_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='money_rewarded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
