# Generated by Django 5.2.17 on 2026-09-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_clientaccountcreatedat_client_client_account_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='money_rewarded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
