# Generated by Django 5.2.17 on 2026-09-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_money_rewarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_password_hash',
            new_name='client_password',
        ),
    ]
